CREATE TABLE RH_SINCRONIZACIONES
(	 
    IdServidorOrigen Integer,
    IdServidorDestino Integer,
    Exportacion Integer,
    Importacion Integer,
    nroLote Integer,
    fecha date,
    IdUsuario Integer,
    fechaResultado date,
    status integer,
	CONSTRAINT "PK_RH_SINCRONIZACIONES" PRIMARY KEY ("IDSERVIDORORIGEN","IDSERVIDORDESTINO", "NROLOTE")
   );
   
-- _____________________________________________________________________________________________

CREATE TABLE RH_SINC_CONFIRMACION
(	 
    IdServidorOrigen Integer,
    IdServidorDestino Integer,
    nroLote Integer,
    fechaResultado date,
	CONSTRAINT "PK_RH_SINC_CONFIRMACION" PRIMARY KEY ("IDSERVIDORORIGEN","IDSERVIDORDESTINO", "NROLOTE")
   );
-- _____________________________________________________________________________________________

CREATE TABLE RH_PERSONAL_LOG_LT 
   ( 
    "NROLOTE" NUMBER NOT NULL ENABLE,
    "STATUS" NUMBER(*,0),
	"ID" NUMBER NOT NULL ENABLE,
    "IDPERSONAL" NUMBER(*,0), 
	"APELLIDO" VARCHAR2(30 BYTE), 
	"NOMBRE" VARCHAR2(40 BYTE), 
	"DNI" NUMBER, 
	"FECHA_NAC" DATE, 
	"SEXO" VARCHAR2(1 BYTE), 
	"CUIL" VARCHAR2(20 BYTE), 
	"SINDICAL" NUMBER, 
	"IDCATEGORIA" NUMBER, 
	"IDESPECIALIDAD" NUMBER, 
	"IDFASE" NUMBER, 
	"LEGAJO" VARCHAR2(30 BYTE), 
	"IDUSUARIOALTA" NUMBER(11,0), 
	"FECHAALTA" DATE, 
	"IDUSUARIOULTMODIF" NUMBER(11,0), 
	"FECHAULTMODIF" DATE, 
	"IDTURNO" NUMBER(*,0), 
	"IDOBRA" NUMBER(11,0), 
	"IDPS" VARCHAR2(20 BYTE), 
	"IDTIPOEMPLEADO" NUMBER(*,0), 
	"FORANEO" NUMBER(*,0), 
	"SUBCONTRATADO" NUMBER(*,0), 
	"IDFUNCION" NUMBER(*,0), 
	"TURNODIURNONOCTURNO" NUMBER(*,0), 
	"IDSUBCONTRATISTA" NUMBER(*,0), 
	"OPERACION" VARCHAR2(10 BYTE), 
	"FECHA" DATE, 
	"IDUSUARIO" NUMBER(*,0), 
	"SALDODIASFRANCO" FLOAT(126), 
	"SALDODIASVACACIONES" FLOAT(126), 
	"IDORIGEN" NUMBER(*,0), 
	"IDCIUDAD" NUMBER(*,0), 
	"DOMICILIO" VARCHAR2(250 BYTE), 
	"IDPROVINCIA" NUMBER(*,0), 
	"MAIL" VARCHAR2(100 BYTE), 
	"TELEFONO1" VARCHAR2(100 BYTE), 
	"TELEFONO2" VARCHAR2(100 BYTE), 
	"RECOMENDADO" VARCHAR2(200 BYTE), 
	"IDREGIMEN_FRANCO" NUMBER(*,0), 
	"IDTIPO_DOCUMENTO" NUMBER(*,0), 
	"IDNACIONALIDAD" NUMBER(*,0), 
	"IDTIPO_TRANSPORTE" NUMBER(*,0), 
	"IDGERENCIA" NUMBER(*,0), 
	"IDFASETRABAJA" NUMBER(*,0), 
	"CALLE" VARCHAR2(100 BYTE), 
	"NUMERO" VARCHAR2(20 BYTE), 
	"PISO" VARCHAR2(10 BYTE), 
	"DEPARTAMENTO" VARCHAR2(10 BYTE), 
	"CODIGOPOSTAL" VARCHAR2(40 BYTE), 
	"EVALUACIONRH" NUMBER(*,0), 
	"DESCRIPCIONEVRH" VARCHAR2(100 BYTE), 
	"IDEVALUADORRH" NUMBER(*,0), 
	"EVALUACIONLD" NUMBER(*,0), 
	"DESCRIPCIONEVLD" VARCHAR2(100 BYTE), 
	"IDEVALUADORLD" NUMBER(*,0), 
	 CONSTRAINT "RH_PERSONAL_LOG_LT_PK" PRIMARY KEY ("ID","NROLOTE")
   );

-- _____________________________________________________________________________________________

  CREATE TABLE RH_INSTANCIA_LOG_LT 
   (	
    "NROLOTE" NUMBER NOT NULL ENABLE,
    "STATUS" NUMBER(*,0),
    "ID" NUMBER NOT NULL ENABLE, 
	"IDINSTANCIA" NUMBER NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(40 BYTE), 
	"IDPERSONAL" NUMBER, 
	"INSTANCIA" VARCHAR2(10 BYTE), 
	"FDESDE" DATE, 
	"FHASTA" DATE, 
	"OPERACION" VARCHAR2(10 BYTE), 
	"FECHA" DATE, 
	"IDUSUARIO" NUMBER(*,0), 
	"IDOBRA" NUMBER(*,0), 
	"MOTIVOBAJA" NUMBER(*,0), 
	"IDMOTIVODESPIDO" NUMBER(*,0), 
	 CONSTRAINT "RH_INSTANCIA_LOG_LT_PK" PRIMARY KEY ("ID", "NROLOTE")
     );

-- ______________________________________________________________________________________________


